version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: "usr"
      POSTGRES_PASSWORD: "pwd"
      PGDATA: /data/postgres
      POSTGRES_DB: "demoDB"
    volumes:
      - ./postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
